services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"